version: '3.1'

services:
  nodeserver:
     build: 
        dockerfile: Dockerfile.frontend 
        context: .
     depends_on:
       - db
     restart: always
     ports:
       - "8000:5000"

  db:
    build: 
        dockerfile: Dockerfile.backend 
        context: .
    restart: always
    ports:
       - "5000:3306"     
